"""add outbox_events table

Revision ID: 2c76a141f938
Revises: edf0cda8ce68
Create Date: 2026-08-10 15:37:54.351124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c76a141f938'
down_revision: Union[str, Sequence[str], None] = 'edf0cda8ce68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payload', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('traffic_stats')
    op.drop_table('product_stats')
    op.drop_table('daily_metrics')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_metrics',
    sa.Column('metric_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('dau', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('view_count', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('purchase_count', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('conversion_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('revenue', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('event_count', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('metric_date', name=op.f('daily_metrics_pkey'))
    )
    op.create_table('product_stats',
    sa.Column('product_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('view_count', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('purchase_count', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('revenue', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.create_table('traffic_stats',
    sa.Column('window_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('window_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('unique_users', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('event_count', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('revenue', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.drop_table('outbox_events')
    # ### end Alembic commands ###
