"""initial schema

Revision ID: f02cd6730977
Revises: 
Create Date: 2026-08-03 17:35:33.881807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f02cd6730977'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('traffic_stats')
    op.drop_table('product_stats')
    op.drop_table('daily_metrics')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_metrics',
    sa.Column('metric_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('dau', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('view_count', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('purchase_count', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('conversion_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('revenue', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('event_count', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('metric_date', name=op.f('daily_metrics_pkey'))
    )
    op.create_table('product_stats',
    sa.Column('product_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('view_count', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('purchase_count', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('revenue', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.create_table('traffic_stats',
    sa.Column('window_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('window_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('unique_users', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('event_count', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('revenue', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
